version: "3.8"
services:
  nextjs-app-prod:
    container_name: nextjs-app-prod
    image: nextjs-app-prod
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - '80:80'
    environment:
      NODE_ENV: production